### ISSUE TITLE
Code for creating a mean for menopause 

### ISSUE THREAD

**Issue by wbea101** [wbea101/Periods-Worldwide#3]
this code works, it transformed my data set and I would like to create a different dataframe with this code

so now transformed data for menopause needs  mean age for each country 
#code for calculating the mean age for menopause in each country 
```{r}
# Load necessary packages
library(dplyr)

# Example data structure (replace this with your actual dataframe)
transformed_data <- data.frame(
  country = c("Tanzania", "Philippines", "Nepal", "Mozambique", "Kenya", "Ghana", "Cote_d'Ivoire,Cam"),
  menopause_age = c(30.34, 35.39, 40.41, 30.34, 35.39, 40.41, 42.43)
)

# Calculate mean age of menopause for each country
mean_menopause_age <- transformed_data %>%
  group_by(country) %>%
  summarise(mean_age = mean(menopause_age, na.rm = TRUE))

# Display the result
print(mean_menopause_age)

**Comment by abhatia08** [comment]
I think this may not be possible with your data, or then we would have to find it elsewhere unfortunately. The code ChatGPT gave you above is actually not very helpful, because it assumes that you have the age of menopause for each person in the country, which would let you simply calculate the average. Because you only have percentage of people that experienced menopause, across different categories of age, this may not be applicable! We may need to think about other avenues to compare menarche and menopause
